### ISSUE TITLE
Project Single Page: Sidebar menu goes down, overlap with content box and changes it's size as you scroll down.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#2]
Project page when first open:
![image](https://cloud.githubusercontent.com/assets/12791909/8797528/a30349e4-2fce-11e5-9856-1cee689cec10.png)

Project page as you scroll down: 
![image](https://cloud.githubusercontent.com/assets/12791909/8797548/b9879198-2fce-11e5-9f35-c93fdb24cce1.png)

**Comment by ramoncebudigital** [comment]
working on my end

**Comment by ermatitan** [comment]
Please see url below. This happens to all long pdf title on the sidebar. 
http://rdaperth.stage.titanweb.com.au/rda-projects/project-2-title-here-for-two-lines-of-more/
