### ISSUE TITLE
Banner Image is cut after a series of banner transistion

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#20]
![image](https://cloud.githubusercontent.com/assets/12791909/8819903/1b35bfaa-3083-11e5-9022-ea203f05e69b.png)

**Comment by ramoncebudigital** [comment]
don't see any issue on my side.

**Comment by ermatitan** [comment]
Changing the label to wontfix from invalid. Issue no longer reproducible in my end. This maybe because of the several banner transition that you have deleted. Thanks
