### ISSUE TITLE
There are are a series of banner description transition settings that will not display the description for 5 seconds. Is this correct?

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#21]
Below are the transition settings that will not display the description for 5seconds

Bounce Out
BounceOutDown
BounceOutLeft
BounceOutRight
BounchOutUP
FadeOutLeft
FadeOutLeftBug
FadeOutRight
FadeOutRightBig
FadeOutUp
FlipOutY
LightSpeedOut
RotateOutUpRight
RotateOut
RotateOutDownLeft
RotateOutDownRight
RotateOutUpLeft
RotateOutUpRight
SlideOutDown
SlideOutLeft
SlideOutRight
ZoomOut
ZoomOutUp
ZoomOutLeft
ZoomOutRight
Hinge
RollOut

**Comment by ramoncebudigital** [comment]
yeah, right!
Already removed in the description transition items
Thanks

**Comment by ermatitan** [comment]
Please also delete the transition below:

flipOutX
flipOutY

**Comment by ramoncebudigital** [comment]
This an enhancement, why did you bug it?
