### ISSUE TITLE
Login menu goes down

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#29]
Device: Samsung tab 3 (Landscape)

![image](https://cloud.githubusercontent.com/assets/12791909/8821279/0c6a2504-308f-11e5-8ce1-38bc05cacfb4.png)

**Comment by ermatitan** [comment]
Not fix. Please see updated screenshot:
![image](https://cloud.githubusercontent.com/assets/12791909/8899786/513a4ca6-346b-11e5-88a3-64bfdb7b65b4.png)

**Comment by ermatitan** [comment]
Not fix. Problem also occurs when you adjust the font size

**Comment by ermatitan** [comment]
Not fix

**Comment by ermatitan** [comment]
Not fix on the actual mobile device

**Comment by ramoncebudigital** [comment]
please try clear cache

**Comment by ermatitan** [comment]
Already cleared my cache, issue still reproducible in the actual mobile device

**Comment by ramoncebudigital** [comment]
since we don't have tab 3 device here, let's leave this issue it for now.
