### ISSUE TITLE
News Single Page : Sidebar misplaced.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#58]
Devices: Ipad, Ipad Air

Portrait
![image](https://cloud.githubusercontent.com/assets/12791909/9034774/f4dac108-3a04-11e5-8db3-f65087450f4f.png)

Landscape

![image](https://cloud.githubusercontent.com/assets/12791909/9034785/045a27b8-3a05-11e5-9a27-1b9f90d80fb1.png)

**Comment by ermatitan** [comment]
Not fix.

**Comment by ramoncebudigital** [comment]
it's working on my side., please try to clear cache or hard refresh (ctr+F5)
thanks.
![screenshot_8](https://cloud.githubusercontent.com/assets/11186436/9081998/8a892b38-3b93-11e5-8230-b9f0324a7b66.png)

**Comment by ermatitan** [comment]
I have cleared my cache. Problem still reproducible in this url 
http://rdaperth.stage.titanweb.com.au/rda-events/event-page-title-here-3/

![image](https://cloud.githubusercontent.com/assets/12791909/9102723/74710d58-3c28-11e5-95fa-2f8c172b2e22.png)
