### ISSUE TITLE
Event Single Page - Location and Date is misplaced on landscape view

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#59]
Device: Ipad Air , Ipad

![image](https://cloud.githubusercontent.com/assets/12791909/9034953/2fb38340-3a06-11e5-9058-fb5e90488963.png)

**Comment by ermatitan** [comment]
Not fix

**Comment by ramoncebudigital** [comment]
it's working on my side., please try to clear cache or hard refresh (ctr+F5)
thanks.
![screenshot_7](https://cloud.githubusercontent.com/assets/11186436/9081794/fc14ded4-3b91-11e5-8e50-2d39b16235cf.png)
