### ISSUE TITLE
Survey pagination design  is not the same with PSD Design

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#6]
![image](https://cloud.githubusercontent.com/assets/12791909/8816680/e2d8f06c-305c-11e5-805a-72d26e83821b.png)

**Comment by ramoncebudigital** [comment]
let's use basic pagination. base on project scope this will apply on all pages with pagination.

**Comment by ermatitan** [comment]
Let follow the design. thanks

**Comment by ramoncebudigital** [comment]
Ok then, talk to Christian with that matters.

**Comment by bernardtitan** [comment]
Erma is not the one who needs to communicate with Christian

**Comment by christiancebudigital** [comment]
Hi  Erma,

this pagination will be basic, this is to make the pagination consistent with the gallery page..

Thanks,
Christian

**Comment by ermatitan** [comment]
Noted christian.. . will close this as wont fix. Thanks
