### ISSUE TITLE
Ipad Air - Overlapping of of test results via landscape view

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#60]
![image](https://cloud.githubusercontent.com/assets/12791909/9051242/8307fd6c-3a8a-11e5-8959-8fe054597dfb.png)

**Comment by ermatitan** [comment]
Not fix

**Comment by ramoncebudigital** [comment]
it's working on my side., please try to clear cache or hard refresh (ctr+F5)
thanks.
![screenshot_6](https://cloud.githubusercontent.com/assets/11186436/9081765/c47b00ca-3b91-11e5-82fc-32fc0aee13cc.png)
