### ISSUE TITLE
Gallery : Album gallery does not meet gallery layout and styles

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#61]
See page:
http://rdaperth.stage.titanweb.com.au/gallery-2/nggallery/sample-album/sample-2

Standard : 5 columns, 4 rows
https://knowledgebase.titanweb.com.au/implementation-practices/nggallery-implementation-practices/gallery-layout-and-styles

![image](https://cloud.githubusercontent.com/assets/12791909/9051264/d5a3c51a-3a8a-11e5-9575-8f6c6a992744.png)

**Comment by ermatitan** [comment]
Not fix, current layout is 6 rows, 4 columns should be  5 columns, 4 rows

**Comment by ramoncebudigital** [comment]
it's working on my side., please try to clear cache or hard refresh (ctr+F5)
thanks.

**Comment by ermatitan** [comment]
Already cleared my cache and  hard refresh (ctr+F5). I can still recreate this issue . Please see my full screen screenshot below:

![gallery 2 - regional development australia 2015-08-06 09-54-52](https://cloud.githubusercontent.com/assets/12791909/9102202/2bb8d790-3c22-11e5-9d2b-89c68310bdee.png)

**Comment by ermatitan** [comment]
Not fix.  Gallery pages still displays 6 rows and 4 colums on my end

**Comment by ramoncebudigital** [comment]
We already agreed with bernard that the default of the gallery images is 24, the knowledge base was not update. Please refer to bernard about this issue
