### ISSUE TITLE
Banner description content box no longer centered after adjusting the font size (+)

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#63]
Device: Samsung S4, ITouch

![image](https://cloud.githubusercontent.com/assets/12791909/9051486/f18d5cde-3a8d-11e5-8f58-e1b7698460d7.png)

**Comment by ramoncebudigital** [comment]
This shouldn't be centered since the desktop view is in the right side.

**Comment by ermatitan** [comment]
The banner content box is now vertically centered and does not overlaps with the banner edge, so I'm changing the label to fix. Thanks
