### ISSUE TITLE
Our Region: 1st repeater: A label without description still displays on  front end.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#66]
Issue also found on the Welcome and Related Links page. 

![image](https://cloud.githubusercontent.com/assets/12791909/9077888/4c480718-3b66-11e5-82b9-7ccc108c1a3c.png)

**Comment by ramoncebudigital** [comment]
added required fields on the backend so that the field wouldn't be empty.

**Comment by ermatitan** [comment]
I have cleared my cache and done a hard refresh, i can still recreate this issue. See full screenshot below:
![our region - regional development australia 2015-08-06 10-10-27](https://cloud.githubusercontent.com/assets/12791909/9102416/7bf418e4-3c24-11e5-94dd-d0cb670ce836.png)
