### ISSUE TITLE
Event Single Page: Proper padding for ordered and unordered list not implemented.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#68]
![image](https://cloud.githubusercontent.com/assets/12791909/9102780/4667fa4c-3c29-11e5-96cb-10a31c9c72b5.png)

**Comment by ramoncebudigital** [comment]
Hi,

This is normal, because the content is not from MSWORD.
see sceenshot:
![screenshot_1](https://cloud.githubusercontent.com/assets/11186436/9188632/dba52112-4010-11e5-9feb-2be3ee83f590.png)
