### ISSUE TITLE
Ipad Air: Inconsistency in sidebar placement in some pages via landscape view. Which is the correct placement of the sidebar on IPAD landscape view?

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#69]
Our region , About RDA , RDA Members and Thank you pages sidebar placement were displayed at the right side of the page while all other pages and ACF post,sidebar was place at the bottom of the page.

![image](https://cloud.githubusercontent.com/assets/12791909/9102922/0288a004-3c2b-11e5-945a-51497a13bd5a.png)

**Comment by ramoncebudigital** [comment]
ok, I will change this to make it consistent to other sidebars.
