### ISSUE TITLE
Event URL is not displayed on the event page and/or the single event page. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#7]
Where should the element event url be displayed on the event page?

**Comment by ramoncebudigital** [comment]
if "Events URL" is not empty it will go to the Event URL site
if empty it will redirect to single page

**Comment by ermatitan** [comment]
I will change the label to "bug" "fixed" since the clicking the find out more button will not go the the event url before.  Thanks
