### ISSUE TITLE
RDA Perth Members ACF sidebar link should be deleted since it is no longer in used.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Regional-Development-Committee#74]
![image](https://cloud.githubusercontent.com/assets/12791909/9191329/81c3b7fe-4032-11e5-92d5-394f3588a7a1.png)

**Comment by ramoncebudigital** [comment]
Sidebar link will display in this section
![screenshot_3](https://cloud.githubusercontent.com/assets/11186436/9215093/a402adf6-40d8-11e5-8536-432241a17ae8.png)

**Comment by ermatitan** [comment]
Hello Ramon, checking on the back-end, About RDA Perth page is using the default template while RDA Perth Members is using the "Member's Page" template. 

Any necessary changes on the RDA Perth Member's page ACF, will be reflected on the About RDA Perth page. You have mistakenly implemented the member's page ACF, it should be on the about us page. All ACF should be reflected to its own page to avoid confusion on the parth of the user/client. Thanks
